db:
  name: db
  replicas: 1
  image: postgres:15-alpine
  containerName: postgres
  user: postgres
  password: postgres
  port: 5432
  mountPath: /var/lib/postgresql/data

redis:
  name: redis
  replicas: 1
  image: redis:alpine
  containerName: redis
  port: 6379
  mountPath: /data

result:
  name: result
  replicas: 4
  image: dockersamples/examplevotingapp_result
  containerName: result
  containerPort: 80
  servicePort: 5001
  nodePort: 31001

vote-chart:
  name: vote
  replicas: 2
  image: dockersamples/examplevotingapp_vote
  containerName: vote
  containerPort: 80
  servicePort: 5000
  nodePort: 31002

worker:
  name: worker
  replicas: 1
  image: dockersamples/examplevotingapp_worker
  containerName: worker
